# state.py


class AgentState:

    def __init__(self, user_input):

        # Original request from the user
        self.user_input = user_input

        # Plan generated by the planner
        self.tasks = []

        # Task currently being executed
        self.current_task = None

        # Results produced by completed tasks
        self.task_results = {}

        # Conversation between agent and LLM
        self.messages = []

        # Safety/control information
        self.iteration = 0
        self.status = "running"

    def add_task_result(self, task, result):

        self.task_results[task.step] = result

    def get_task_result(self, step):

        return self.task_results.get(step)